services:
  - type: web
    name: mi-microservicio-springboot
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
    numInstances: 1