server:
  port: ${PORT:8082}

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://dpg-d40fp9d5bbfc73dl2m60-a.oregon-postgres.render.com:5432/microservicesdb_kum6
    username: microservices_admin
    password: Jf62SSkS4Kx3UqPIZQK0wEdMp4STS8SH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.microservices.product: INFO